### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by cnk113** [Nawijn-Group-Bioinformatics/FastCAR#1]
Hello,

I read your preprint and your approach sounds very promising! I did have a few questions on the input, can we use non integer counts from pseudoaligners? Also did you try to denoise spliced and unspliced counts as well? And for the iteration value, I've set the max iteration to 200, did you generally need to push the max higher?

Best,
Chang

**Comment by MarijnBerg** [comment]
Hi Chang, 

Unfortunately non-integer counts aren't supported at the time but if you have a specific method in mind I can have a look to see if it'd be compatible.

I havent' tried the method on spliced and unspliced counts, I think it could work with some slight modification but I see little reason to do so as this method is mostly meant for make DGE results more accurate.

So for the max I've used in practice is 150, and that was on whole biopsy material with very noticeable ambient RNA effects.

Best wishes,
Marijn
